Allow any version of @types/node
This fixes a typescript error when a newer @types/node is installed along with passport-ldapauth.

tsc errosr:
node_modules/ldapauth-fork/lib/ldapauth.d.ts:6:23 - error TS4090: Conflicting definitions for 'node' found at '***/node_modules/ldapauth-fork/node_modules/@types/node/ts3.2/index.d.ts' and '***/node_modules/@types/node/ts3.5/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

6 /// <reference types="node"/>
                        ~~~~

node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.d.ts:6:23 - error TS4090: Conflicting definitions for 'node' found at '***/node_modules/passport-ldapauth/node_modules/@types/node/ts3.2/index.d.ts' and '***/node_modules/@types/node/ts3.5/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

6 /// <reference types="node"/>
                        ~~~~


Found 2 errors.